// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Other.proto

package com.mogujie.tt.protobuf;

public final class IMOther {
  private IMOther() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface IMHeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Other.IMHeartBeat)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * <pre>
   *cmd id:  		0x0701
   * </pre>
   *
   * Protobuf type {@code IM.Other.IMHeartBeat}
   */
  public  static final class IMHeartBeat extends
      com.google.protobuf.GeneratedMessageLite<
          IMHeartBeat, IMHeartBeat.Builder> implements
      // @@protoc_insertion_point(message_implements:IM.Other.IMHeartBeat)
      IMHeartBeatOrBuilder {
    private IMHeartBeat() {
    }
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.IMOther.IMHeartBeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *cmd id:  		0x0701
     * </pre>
     *
     * Protobuf type {@code IM.Other.IMHeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.IMOther.IMHeartBeat, Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Other.IMHeartBeat)
        com.mogujie.tt.protobuf.IMOther.IMHeartBeatOrBuilder {
      // Construct using com.mogujie.tt.protobuf.IMOther.IMHeartBeat.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:IM.Other.IMHeartBeat)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.IMOther.IMHeartBeat();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.IMOther.IMHeartBeat other = (com.mogujie.tt.protobuf.IMOther.IMHeartBeat) arg1;
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.IMOther.IMHeartBeat.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:IM.Other.IMHeartBeat)
    private static final com.mogujie.tt.protobuf.IMOther.IMHeartBeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IMHeartBeat();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<IMHeartBeat> PARSER;

    public static com.google.protobuf.Parser<IMHeartBeat> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface IMCarInfoReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Other.IMCarInfoReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *消息发送id
     * </pre>
     *
     * <code>required uint64 user_id = 1;</code>
     */
    boolean hasUserId();
    /**
     * <pre>
     *消息发送id
     * </pre>
     *
     * <code>required uint64 user_id = 1;</code>
     */
    long getUserId();

    /**
     * <pre>
     *用户信息数据
     * </pre>
     *
     * <code>optional bytes user_info = 2;</code>
     */
    boolean hasUserInfo();
    /**
     * <pre>
     *用户信息数据
     * </pre>
     *
     * <code>optional bytes user_info = 2;</code>
     */
    com.google.protobuf.ByteString getUserInfo();

    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    boolean hasAttachData();
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    com.google.protobuf.ByteString getAttachData();
  }
  /**
   * Protobuf type {@code IM.Other.IMCarInfoReq}
   */
  public  static final class IMCarInfoReq extends
      com.google.protobuf.GeneratedMessageLite<
          IMCarInfoReq, IMCarInfoReq.Builder> implements
      // @@protoc_insertion_point(message_implements:IM.Other.IMCarInfoReq)
      IMCarInfoReqOrBuilder {
    private IMCarInfoReq() {
      userInfo_ = com.google.protobuf.ByteString.EMPTY;
      attachData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <pre>
     *消息发送id
     * </pre>
     *
     * <code>required uint64 user_id = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *消息发送id
     * </pre>
     *
     * <code>required uint64 user_id = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }
    /**
     * <pre>
     *消息发送id
     * </pre>
     *
     * <code>required uint64 user_id = 1;</code>
     */
    private void setUserId(long value) {
      bitField0_ |= 0x00000001;
      userId_ = value;
    }
    /**
     * <pre>
     *消息发送id
     * </pre>
     *
     * <code>required uint64 user_id = 1;</code>
     */
    private void clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = 0L;
    }

    public static final int USER_INFO_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString userInfo_;
    /**
     * <pre>
     *用户信息数据
     * </pre>
     *
     * <code>optional bytes user_info = 2;</code>
     */
    public boolean hasUserInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *用户信息数据
     * </pre>
     *
     * <code>optional bytes user_info = 2;</code>
     */
    public com.google.protobuf.ByteString getUserInfo() {
      return userInfo_;
    }
    /**
     * <pre>
     *用户信息数据
     * </pre>
     *
     * <code>optional bytes user_info = 2;</code>
     */
    private void setUserInfo(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      userInfo_ = value;
    }
    /**
     * <pre>
     *用户信息数据
     * </pre>
     *
     * <code>optional bytes user_info = 2;</code>
     */
    private void clearUserInfo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      userInfo_ = getDefaultInstance().getUserInfo();
    }

    public static final int ATTACH_DATA_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString attachData_;
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public boolean hasAttachData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public com.google.protobuf.ByteString getAttachData() {
      return attachData_;
    }
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    private void setAttachData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      attachData_ = value;
    }
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    private void clearAttachData() {
      bitField0_ = (bitField0_ & ~0x00000004);
      attachData_ = getDefaultInstance().getAttachData();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, userInfo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(20, attachData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, userInfo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, attachData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.IMOther.IMCarInfoReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code IM.Other.IMCarInfoReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.IMOther.IMCarInfoReq, Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Other.IMCarInfoReq)
        com.mogujie.tt.protobuf.IMOther.IMCarInfoReqOrBuilder {
      // Construct using com.mogujie.tt.protobuf.IMOther.IMCarInfoReq.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *消息发送id
       * </pre>
       *
       * <code>required uint64 user_id = 1;</code>
       */
      public boolean hasUserId() {
        return instance.hasUserId();
      }
      /**
       * <pre>
       *消息发送id
       * </pre>
       *
       * <code>required uint64 user_id = 1;</code>
       */
      public long getUserId() {
        return instance.getUserId();
      }
      /**
       * <pre>
       *消息发送id
       * </pre>
       *
       * <code>required uint64 user_id = 1;</code>
       */
      public Builder setUserId(long value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <pre>
       *消息发送id
       * </pre>
       *
       * <code>required uint64 user_id = 1;</code>
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }

      /**
       * <pre>
       *用户信息数据
       * </pre>
       *
       * <code>optional bytes user_info = 2;</code>
       */
      public boolean hasUserInfo() {
        return instance.hasUserInfo();
      }
      /**
       * <pre>
       *用户信息数据
       * </pre>
       *
       * <code>optional bytes user_info = 2;</code>
       */
      public com.google.protobuf.ByteString getUserInfo() {
        return instance.getUserInfo();
      }
      /**
       * <pre>
       *用户信息数据
       * </pre>
       *
       * <code>optional bytes user_info = 2;</code>
       */
      public Builder setUserInfo(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserInfo(value);
        return this;
      }
      /**
       * <pre>
       *用户信息数据
       * </pre>
       *
       * <code>optional bytes user_info = 2;</code>
       */
      public Builder clearUserInfo() {
        copyOnWrite();
        instance.clearUserInfo();
        return this;
      }

      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public boolean hasAttachData() {
        return instance.hasAttachData();
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public com.google.protobuf.ByteString getAttachData() {
        return instance.getAttachData();
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder setAttachData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAttachData(value);
        return this;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder clearAttachData() {
        copyOnWrite();
        instance.clearAttachData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Other.IMCarInfoReq)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.IMOther.IMCarInfoReq();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasUserId()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.IMOther.IMCarInfoReq other = (com.mogujie.tt.protobuf.IMOther.IMCarInfoReq) arg1;
          userId_ = visitor.visitLong(
              hasUserId(), userId_,
              other.hasUserId(), other.userId_);
          userInfo_ = visitor.visitByteString(
              hasUserInfo(), userInfo_,
              other.hasUserInfo(), other.userInfo_);
          attachData_ = visitor.visitByteString(
              hasAttachData(), attachData_,
              other.hasAttachData(), other.attachData_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  userId_ = input.readUInt64();
                  break;
                }
                case 18: {
                  bitField0_ |= 0x00000002;
                  userInfo_ = input.readBytes();
                  break;
                }
                case 162: {
                  bitField0_ |= 0x00000004;
                  attachData_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.IMOther.IMCarInfoReq.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:IM.Other.IMCarInfoReq)
    private static final com.mogujie.tt.protobuf.IMOther.IMCarInfoReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IMCarInfoReq();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<IMCarInfoReq> PARSER;

    public static com.google.protobuf.Parser<IMCarInfoReq> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface IMCarInfoRepOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Other.IMCarInfoRep)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
     */
    com.mogujie.tt.protobuf.IMBaseDefine.ResultType getResultCode();

    /**
     * <code>required uint64 user_id = 2;</code>
     */
    boolean hasUserId();
    /**
     * <code>required uint64 user_id = 2;</code>
     */
    long getUserId();

    /**
     * <code>optional bytes return_info = 3;</code>
     */
    boolean hasReturnInfo();
    /**
     * <code>optional bytes return_info = 3;</code>
     */
    com.google.protobuf.ByteString getReturnInfo();

    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    boolean hasAttachData();
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    com.google.protobuf.ByteString getAttachData();
  }
  /**
   * Protobuf type {@code IM.Other.IMCarInfoRep}
   */
  public  static final class IMCarInfoRep extends
      com.google.protobuf.GeneratedMessageLite<
          IMCarInfoRep, IMCarInfoRep.Builder> implements
      // @@protoc_insertion_point(message_implements:IM.Other.IMCarInfoRep)
      IMCarInfoRepOrBuilder {
    private IMCarInfoRep() {
      returnInfo_ = com.google.protobuf.ByteString.EMPTY;
      attachData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int RESULT_CODE_FIELD_NUMBER = 1;
    private int resultCode_;
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
     */
    public com.mogujie.tt.protobuf.IMBaseDefine.ResultType getResultCode() {
      com.mogujie.tt.protobuf.IMBaseDefine.ResultType result = com.mogujie.tt.protobuf.IMBaseDefine.ResultType.forNumber(resultCode_);
      return result == null ? com.mogujie.tt.protobuf.IMBaseDefine.ResultType.REFUSE_REASON_NONE : result;
    }
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
     */
    private void setResultCode(com.mogujie.tt.protobuf.IMBaseDefine.ResultType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      resultCode_ = value.getNumber();
    }
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
     */
    private void clearResultCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      resultCode_ = 0;
    }

    public static final int USER_ID_FIELD_NUMBER = 2;
    private long userId_;
    /**
     * <code>required uint64 user_id = 2;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 user_id = 2;</code>
     */
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>required uint64 user_id = 2;</code>
     */
    private void setUserId(long value) {
      bitField0_ |= 0x00000002;
      userId_ = value;
    }
    /**
     * <code>required uint64 user_id = 2;</code>
     */
    private void clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      userId_ = 0L;
    }

    public static final int RETURN_INFO_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString returnInfo_;
    /**
     * <code>optional bytes return_info = 3;</code>
     */
    public boolean hasReturnInfo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes return_info = 3;</code>
     */
    public com.google.protobuf.ByteString getReturnInfo() {
      return returnInfo_;
    }
    /**
     * <code>optional bytes return_info = 3;</code>
     */
    private void setReturnInfo(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      returnInfo_ = value;
    }
    /**
     * <code>optional bytes return_info = 3;</code>
     */
    private void clearReturnInfo() {
      bitField0_ = (bitField0_ & ~0x00000004);
      returnInfo_ = getDefaultInstance().getReturnInfo();
    }

    public static final int ATTACH_DATA_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString attachData_;
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public boolean hasAttachData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public com.google.protobuf.ByteString getAttachData() {
      return attachData_;
    }
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    private void setAttachData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      attachData_ = value;
    }
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    private void clearAttachData() {
      bitField0_ = (bitField0_ & ~0x00000008);
      attachData_ = getDefaultInstance().getAttachData();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, resultCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, returnInfo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(20, attachData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, resultCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, returnInfo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, attachData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.IMOther.IMCarInfoRep prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code IM.Other.IMCarInfoRep}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.IMOther.IMCarInfoRep, Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Other.IMCarInfoRep)
        com.mogujie.tt.protobuf.IMOther.IMCarInfoRepOrBuilder {
      // Construct using com.mogujie.tt.protobuf.IMOther.IMCarInfoRep.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
       */
      public boolean hasResultCode() {
        return instance.hasResultCode();
      }
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
       */
      public com.mogujie.tt.protobuf.IMBaseDefine.ResultType getResultCode() {
        return instance.getResultCode();
      }
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
       */
      public Builder setResultCode(com.mogujie.tt.protobuf.IMBaseDefine.ResultType value) {
        copyOnWrite();
        instance.setResultCode(value);
        return this;
      }
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
       */
      public Builder clearResultCode() {
        copyOnWrite();
        instance.clearResultCode();
        return this;
      }

      /**
       * <code>required uint64 user_id = 2;</code>
       */
      public boolean hasUserId() {
        return instance.hasUserId();
      }
      /**
       * <code>required uint64 user_id = 2;</code>
       */
      public long getUserId() {
        return instance.getUserId();
      }
      /**
       * <code>required uint64 user_id = 2;</code>
       */
      public Builder setUserId(long value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <code>required uint64 user_id = 2;</code>
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }

      /**
       * <code>optional bytes return_info = 3;</code>
       */
      public boolean hasReturnInfo() {
        return instance.hasReturnInfo();
      }
      /**
       * <code>optional bytes return_info = 3;</code>
       */
      public com.google.protobuf.ByteString getReturnInfo() {
        return instance.getReturnInfo();
      }
      /**
       * <code>optional bytes return_info = 3;</code>
       */
      public Builder setReturnInfo(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setReturnInfo(value);
        return this;
      }
      /**
       * <code>optional bytes return_info = 3;</code>
       */
      public Builder clearReturnInfo() {
        copyOnWrite();
        instance.clearReturnInfo();
        return this;
      }

      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public boolean hasAttachData() {
        return instance.hasAttachData();
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public com.google.protobuf.ByteString getAttachData() {
        return instance.getAttachData();
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder setAttachData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAttachData(value);
        return this;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder clearAttachData() {
        copyOnWrite();
        instance.clearAttachData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Other.IMCarInfoRep)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.IMOther.IMCarInfoRep();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasResultCode()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasUserId()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.IMOther.IMCarInfoRep other = (com.mogujie.tt.protobuf.IMOther.IMCarInfoRep) arg1;
          resultCode_ = visitor.visitInt(hasResultCode(), resultCode_,
              other.hasResultCode(), other.resultCode_);
          userId_ = visitor.visitLong(
              hasUserId(), userId_,
              other.hasUserId(), other.userId_);
          returnInfo_ = visitor.visitByteString(
              hasReturnInfo(), returnInfo_,
              other.hasReturnInfo(), other.returnInfo_);
          attachData_ = visitor.visitByteString(
              hasAttachData(), attachData_,
              other.hasAttachData(), other.attachData_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  int rawValue = input.readEnum();
                  com.mogujie.tt.protobuf.IMBaseDefine.ResultType value = com.mogujie.tt.protobuf.IMBaseDefine.ResultType.forNumber(rawValue);
                  if (value == null) {
                    super.mergeVarintField(1, rawValue);
                  } else {
                    bitField0_ |= 0x00000001;
                    resultCode_ = rawValue;
                  }
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  userId_ = input.readUInt64();
                  break;
                }
                case 26: {
                  bitField0_ |= 0x00000004;
                  returnInfo_ = input.readBytes();
                  break;
                }
                case 162: {
                  bitField0_ |= 0x00000008;
                  attachData_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.IMOther.IMCarInfoRep.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:IM.Other.IMCarInfoRep)
    private static final com.mogujie.tt.protobuf.IMOther.IMCarInfoRep DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IMCarInfoRep();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<IMCarInfoRep> PARSER;

    public static com.google.protobuf.Parser<IMCarInfoRep> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
